Format docx pour lettre
spyrales/quarto-gouv pull request #1
Opened 2022-10-14 10:25 UTC by cdugeai

Création d'un format de sortie `.docx` pour la génération d'une lettre.

2022-10-14 10:27 UTC, cdugeai commented
Exemple de fichier généré par cette commande, avec le `template.qmd` du repo:

https://github.com/spyrales/quarto-gouv/blob/0b27d3bc0e870208a87909d360fc260f05cdbe6e/README.md?plain=1#L13


[test_render.docx](https://github.com/spyrales/quarto-gouv/files/9785148/test_render.docx)

2022-10-17 16:24 UTC, RLesur requested changes
Quelques commentaires et une question supplémentaire : je me demande s'il ne faudrait pas adopter un autre nom pour le répertoire, je mettrais bien `lettre-gouv` au lieu de `quarto-gouv`, non ?

2022-10-17 16:24 UTC, RLesur commented on _extensions/quarto-gouv/_extension.yml
> +title: Onyxia Presentation (light theme)
```suggestion
title: Lettre Word
```

2022-10-17 16:24 UTC, RLesur commented on _extensions/quarto-gouv/_extension.yml
> +author: Romain Lesur
```suggestion
author: Colin Dugeai
```

2022-10-17 16:24 UTC, RLesur commented on _extensions/quarto-gouv/_extension.yml
> +version: 1.1.0
```suggestion
version: 1.0.0
```

2022-10-17 16:24 UTC, RLesur commented on _extensions/quarto-gouv/_extension.yml
> +      highlight-style: github
ajouter une ligne vide à la fin du fichier :

```suggestion
      highlight-style: github

```

2022-10-17 16:24 UTC, RLesur commented on template.qmd
> +<div custom-style="Date">
ce serait mieux d'utiliser les native divs de pandoc, non ?

2022-10-18 09:16 UTC, ThomasFaria requested changes
Un problème à régler avec le dossier ```out``` et une petite suggestion

2022-10-18 09:16 UTC, ThomasFaria commented on .gitignore
> +out/
Il faudrait rajouter un .gitkeep dans le folder ```out``` ou alors ne pas sauvegarder notre fichier final dans ce dossier sinon on obtient une erreur après le clone

2022-10-18 09:16 UTC, ThomasFaria commented on README.md
> +
Peut-être anticiper le fait qu'on aura plusieurs formats à terme (docs, ppt...)

```suggestion

## Formats

The following formats have been implemented so far.

### docx

```

2022-10-18 09:25 UTC, ThomasFaria reviewed
coquille

2022-10-18 09:25 UTC, ThomasFaria commented on template.qmd
> +  destinataire_titre: "Madame la préfête de la Loire-Atlantique"
coquille 
```suggestion
  destinataire_titre: "Madame la préfète de la Loire-Atlantique"
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="Date">
```suggestion
::: {custom-style="Date"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +</div>
```suggestion
:::
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="subheader-annexe">
```suggestion
::: {custom-style="subheader-annexe"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="header-annexeN">
```suggestion
::: {custom-style="header-annexeN"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="Compact">
```suggestion
::: {custom-style="Compact"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="objet-title">
```suggestion
::: {custom-style="objet-title"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="header-letter-naming">
```suggestion
::: {custom-style="header-letter-naming"}
```

2022-10-18 13:32 UTC, ThomasFaria commented on template.qmd
> +<div custom-style="header-letter">
```suggestion
::: {custom-style="header-letter"}
```

2022-10-18 13:45 UTC, RLesur commented on template.qmd
> +<div style="header-annexes">
```suggestion
::: {style="header-annexes"}
```

2022-10-18 13:46 UTC, RLesur approved these changes

2022-10-18 13:46 UTC, ThomasFaria approved these changes

2022-10-18 13:47 UTC, merged